### ISSUE TITLE
auro-icon: add pictographs

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/Icons#267] opened 2024-08-20 21:14 UTC
### Is your feature request related to a problem? Please describe.

Pictographs are used across pages, and a design library in Figma already exists.

### Describe the solution you'd like

A collection of pictographs that would be available for devs to use when designers use it in their designs.

**Comment by jason-capsule42** [comment] 2024-10-27 03:42
Closing as a duplicate of #129

**Closed by jason-capsule42** 2024-10-27 03:42 UTC
Labels: Type: Feature
